name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      
      - name: "SSH to server"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ec2-13-213-123-113.ap-southeast-1.compute.amazonaws.com

      - name: "Check cmd"
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-213-123-113.ap-southeast-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl status
            docker ps -a
