name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - uses: appleboy/ssh-action@master
        with:
          host: ec2-18-139-49-151.ap-southeast-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          
      - name: "SSH to server"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ec2-18-139-49-151.ap-southeast-1.compute.amazonaws.com

      - name: "Check cmd"     
        run: |
          systemctl status
          docker ps -a
